name: Continuous Integration

on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        mkdir out
        /opt/devkitpro/devkitPPC/bin/powerpc-eabi-as -mgekko -mregnames ./source/mario_kart_wii_remote_code_execution.S -o ./out/mario_kart_wii_remote_code_execution.o
        /opt/devkitpro/devkitPPC/bin/powerpc-eabi-ld -Ttext 0x80000000 ./out/mario_kart_wii_remote_code_execution.o
        /opt/devkitpro/devkitPPC/bin/powerpc-eabi-objcopy -O binary ./out/mario_kart_wii_remote_code_execution.o ./out/mario_kart_wii_remote_code_execution.bin

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Releases
        path: ./out/mario_kart_wii_remote_code_execution.bin
